### ISSUE TITLE
find in the start_x.bat cannot work 

### ISSUE THREAD

**Issue by ll550** [iic-jku/IIC-OSIC-TOOLS#16]
**Describe the bug**
when run the start_x.bat with a cotainner running, the find function is not working in the command prompt.

docker container inspect %CONTAINER_NAME% 2>&1 | find "Status" | find /i "running"
find: '/i': No such file or directory
find:find :'Status' : 'running'No such file or directory:
No such file or directory

Replacing the find by findstr, everything is OK

**To Reproduce**
Let the docker image running, type start_x.bat in the command prompt.

**Expected behavior**
The batch file is supposed to find the running status correctly.

**Screenshots**

**Environment:**
 - OS: Win10
 - Operating mode: X11
 - Version tag: latest

**Additional context**

**Comment by hpretl** [comment]
@MrHighVoltage Can you please take a look and fix? Thx!

**Comment by MrHighVoltage** [comment]
Hi, yes I will take a look. Very interesting that this doen't work anymore, because I probably tested this.
Thank you for the Issue, I'm looking at it and keep you updated.

**Comment by MrHighVoltage** [comment]
So I just tested it on a Windows machine and looked into find vs. findstr and it seems that findstr just introduces Regex to find. @ll550, could you maybe give me more information, which shell are you using etc.?

**Comment by ll550** [comment]
@MrHighVoltage hi 
I just used cmd.exe, which is offered by the os win10.

**Comment by MrHighVoltage** [comment]
That is very interesting, because it works on two different machines for me. @ll550 Do you maybe have some kind of Unix-Environment installed? Like cygwin? It could happen that it overwrites the "windows find" with the "cygwin find". You can checkt that with "which find".

Anyways, I'll change it to findstr, which seems to be more robust if something like that happens, because there is no findstr in the unix world, afaik.

**Comment by ll550** [comment]
@MrHighVoltage  Yes, you are right. I used to install msys64 in the computer and leave it for nothing. Sorry to bother.
